version: "3"
services:
  prometheus:
    network_mode: "host"
    image: prom/prometheus
    expose:
      - 9090
    # ports:
    # - 9090:9090
    volumes:
      - "./prometheus-config.yaml:/etc/prometheus/prometheus.yml"

  grafana:
    network_mode: "host"
    image: grafana/grafana
    expose:
      - 3000
    # ports:
    # - 3000:3000
    volumes:
      - "./prometheus-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yml"
