# This file provisions datasources when grafana is starting.
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://127.0.0.1:9090
    isDefault:
    version: 1
    editable: true
